{pkgs, ...}: {  
  environment.systemPackages = with pkgs; [
    nh
    lf
    git
    bat
    vim
    meow
    spek
    htop
    tree
    btop
    fish
    curl
    nixd
    yazi
    emacs
    kitty
    oxker
    whois
    direnv
    cowsay
    lolcat
    bottom
    ntfs3g
    csvlens
    busybox
    openocd
    rustfmt
    pkgconf
    hyfetch
    lazygit
    ripgrep
    onefetch
    lemonade
    wash-cli
    binsider
    keycloak
    pgadmin4
    notonoto
    firejail
    pciutils
    usbutils
    sqlx-cli
    scope-tui
    alejandra
    man-pages
    postgresql
    font-alias
    noto-fonts
    # mullvad-vpn    
    nixpkgs-fmt
    rust-analyzer
    man-pages-posix
    mullvad-browser
    mullvad-compass    
    gnome-disk-utility
    bluez-experimental
    python312Packages.pip
    noto-fonts-color-emoji

    netbird
    netbird-ui
    netbird-dashboard
    netbird-management
  ];
 
  users.users.yago = {
    isNormalUser = true;
    shell = pkgs.fish;
    description = "Kamol Khakimov";
    extraGroups = [
      "networkmanager"
      "wireshark"
      "wheel"
    ];
    packages = with pkgs; [
      # Network
      dig
      wget
      zeek
      trippy
      snicat
      netcat
      tshark
      tcpdump
      nethack
      suricata
      bandwhich
      inetutils

      vlc
      #nyxt
      anki
      gimp
      emacs
      #lmms
      #nheko
      #kicad
      #krita
      docker
      #ardour
      fractal
      element
      keymapp
      discord
      spotify
      #blender
      obsidian
      #gccgo14
      audacity
      gns3-gui
      #guitarix
      #openscad
      librewolf
      wireshark
      dockerfmt
      proton-vpn
      obs-studio
      element-web
      thunderbird
      qbittorrent
      yandex-music
      docker-compose
      element-desktop
      #pkgs.nerdfonts
      telegram-desktop
      jetbrains-toolbox
      #libsForQt5.kamoso
      #ciscoPacketTracer8
      #ciscoPacketTracer7
      docker-color-output
      libreoffice-qt6-still
      dockerfile-language-server

      
      kdePackages.akregator      
      kdePackages.alligator
      kdePackages.bovo
      kdePackages.falkon
      kdePackages.filelight
      kdePackages.francis
      kdePackages.ghostwriter
      kdePackages.isoimagewriter
      kdePackages.kalarm
      kdePackages.kalgebra
      kdePackages.kamera
      kdePackages.kamoso
      kdePackages.kapman
      kdePackages.karousel
      kdePackages.kasts
      kdePackages.kate
      kdePackages.katomic
      kdePackages.kbackup
      kdePackages.kcachegrind      
      kdePackages.kclock
      kdePackages.kcolorchooser
      kdePackages.kcolorpicker
      kdePackages.kdenlive
      kdePackages.kfind      
      kdePackages.kget
      kdePackages.kigo
      kdePackages.kmahjongg
      kdePackages.kmplot
      kdePackages.knavalbattle
      kdePackages.knetwalk
      kdePackages.kolourpaint
      kdePackages.konqueror
      kdePackages.konquest
      kdePackages.konversation
      kdePackages.krdc
      kdePackages.kreversi
      kdePackages.krfb      
      kdePackages.kruler
      kdePackages.kshisen
      kdePackages.ksirk
      kdePackages.ksudoku
      kdePackages.ksystemlog
      kdePackages.ksystemstats
      kdePackages.kteatime
      kdePackages.ktorrent
      kdePackages.ktouch
      kdePackages.marble
      kdePackages.minuet
      kdePackages.neochat      
      kdePackages.palapeli
      kdePackages.step
      kdePackages.umbrello
      kdePackages.yakuake
    ];
  };
}
