# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-3de86fb8-1d51-4d40-827b-6bcae0c0939b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-3de86fb8-1d51-4d40-827b-6bcae0c0939b".device = "/dev/disk/by-uuid/3de86fb8-1d51-4d40-827b-6bcae0c0939b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0008-4F93";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-2c20d866-584a-4f7e-8ba8-b5422eb4deca"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
