;; Custom startup
(add-hook 'emacs-startup-hook
	  (lambda () 
	    (let* ((buffer-hello (get-buffer-create ":3"))) 
	      (switch-to-buffer buffer-hello)
	      (insert "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
	      (insert "")
	      ;; (disable-command )
	      (insert "\n")
	      (center-paragraph)
	      (toggle-truncate-lines)
	      (delete-other-windows) 
	      (message "There is only time. A circular pattern, a hex I abide ") 
	      (buffer-modified-p) 
	      (read-only-mode))))
